FROM ubuntu:24.04 AS build

# Prep the packaged directories.
RUN mkdir -p /rootfs/etc
RUN mkdir -p /rootfs/run
RUN mkdir -p /rootfs/usr/lib

# Prepare special-mode directories.
RUN mkdir -p -m 1777 /rootfs/tmp
RUN mkdir -p -m 1777 /rootfs/run/lock
RUN mkdir -p -m 1777 /rootfs/var/tmp

# Package default symlinks.
RUN ln -s usr/bin   /rootfs/bin
RUN ln -s usr/lib   /rootfs/lib
RUN ln -s usr/sbin  /rootfs/sbin
RUN ln -s /run      /rootfs/var/run
RUN ln -s /run/lock /rootfs/var/lock

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
    mariadb-server

RUN DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
    pax-utils rsync

# Package up binaries.
RUN cp --parents /usr/sbin/mariadbd   /rootfs
RUN cp --parents /usr/bin/sh \
                 /usr/bin/mariadb* \
                 /usr/bin/mysql* \
                 /usr/bin/my_print_defaults \
                 rootfs

# Package up the libraries.
RUN find /rootfs/usr/bin -type f -exec lddtree --copy-to-tree /rootfs '{}' \;
RUN find /rootfs/usr/sbin -type f -exec lddtree --copy-to-tree /rootfs '{}' \;

RUN mkdir -p /rootfs/run/mysqld && chown mysql /rootfs/run/mysqld
RUN mkdir -p /rootfs/var/lib/mysql && chown mysql:mysql /rootfs/var/lib/mysql

FROM scratch
LABEL role=mariadb
# LABEL version=1.6.24

COPY --from=build /rootfs              /
COPY --from=build /etc/group           /etc/group
COPY --from=build /etc/mysql           /etc/mysql
COPY --from=build /etc/passwd          /etc/passwd
COPY --from=build /usr/lib/mysql       /usr/lib/mysql
COPY --from=build /usr/share/mysql     /usr/share/mysql
COPY --from=build /var/lib/mysql       /var/lib/mysql

EXPOSE 3306
USER mysql
ENTRYPOINT [ "/usr/sbin/mariadbd" ]
