FROM ubuntu:24.04 AS build

# Prep the packaged directories.
RUN mkdir -p /rootfs/etc
RUN mkdir -p /rootfs/run
RUN mkdir -p /rootfs/usr/lib

# Prepare special-mode directories.
RUN mkdir -p -m 1777 /rootfs/tmp
RUN mkdir -p -m 1777 /rootfs/run/lock
RUN mkdir -p -m 1777 /rootfs/var/tmp

# Package default symlinks.
RUN ln -s usr/bin   /rootfs/bin
RUN ln -s usr/lib   /rootfs/lib
RUN ln -s usr/sbin  /rootfs/sbin
RUN ln -s /run      /rootfs/var/run
RUN ln -s /run/lock /rootfs/var/lock

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
    memcached

RUN DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
    pax-utils rsync

# Package up the libraries.
RUN lddtree --copy-to-tree /rootfs /usr/bin/memcached

RUN mkdir -p /rootfs/run/memcached && chown memcache /rootfs/run/memcached

FROM scratch
LABEL role=memcached
LABEL version=1.6.24

COPY --from=build /rootfs                  /
COPY --from=build /etc/group               /etc/group
COPY --from=build /etc/passwd              /etc/passwd
COPY --from=build /etc/default/memcached   /etc/default/memcached
COPY --from=build /etc/memcached.conf      /etc/memcached.conf
COPY --from=build /usr/bin/memcached       /usr/bin/memcached

EXPOSE 11211
USER memcache
ENTRYPOINT [ "/usr/bin/memcached" ]
