FROM ubuntu:24.04 AS build

# Prep the packaged directories.
RUN mkdir -p /rootfs/etc
RUN mkdir -p /rootfs/run
RUN mkdir -p /rootfs/usr/lib

# Prepare special-mode directories.
RUN mkdir -p -m 1777 /rootfs/tmp
RUN mkdir -p -m 1777 /rootfs/run/lock
RUN mkdir -p -m 1777 /rootfs/var/tmp

# Package default symlinks.
RUN ln -s usr/bin   /rootfs/bin
RUN ln -s usr/lib   /rootfs/lib
RUN ln -s usr/sbin  /rootfs/sbin
RUN ln -s /run      /rootfs/var/run
RUN ln -s /run/lock /rootfs/var/lock

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
    apache2

RUN DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
    pax-utils rsync

# Package up required shell utilities.
RUN mkdir -p /rootfs/usr/bin
RUN cp --parents /usr/bin/awk \
                 /usr/bin/chown \
                 /usr/bin/chmod \
                 /usr/bin/id \
                 /usr/bin/mkdir \
                 /usr/bin/mktemp \
                 /usr/bin/mv \
                 /usr/bin/readlink \
                 /usr/bin/rmdir \
                 /usr/bin/sh \
                 /usr/bin/stat \
                 /rootfs
# Package up apache binaries.
RUN cp --parents /usr/sbin/apache2 \
                 /usr/sbin/apache2ctl \
                 rootfs

# Package up the libraries.
RUN find /rootfs/usr/bin -type f -exec lddtree --copy-to-tree /rootfs '{}' \;
RUN find /rootfs/usr/sbin -type f -exec lddtree --copy-to-tree /rootfs '{}' \;
RUN find /usr/lib/apache2 -type f -name '*.so*' -exec lddtree --copy-to-tree /rootfs '{}' \;

# Apache requires the mime definitions from etc.
RUN cp --parents /etc/mime.types /rootfs

RUN mkdir -p /rootfs/run/apache2 && chown www-data:www-data /rootfs/run/apache2
RUN mkdir -p /rootfs/var/www/html && chown www-data:www-data /rootfs/var/www/html

# Redirect default logs to stdout.
RUN mkdir -p /rootfs/var/log/apache2 && chown www-data:www-data /rootfs/var/log/apache2
RUN ln -sf /dev/stdout /rootfs/var/log/apache2/access.log && \
    ln -sf /dev/stdout /rootfs/var/log/apache2/error.log

FROM scratch
LABEL role=apache2
LABEL version=2.4.58

COPY --from=build /rootfs              /
COPY --from=build /etc/apache2         /etc/apache2
COPY --from=build /etc/group           /etc/group
COPY --from=build /etc/passwd          /etc/passwd
COPY --from=build /usr/share/apache2   /usr/share/apache2
COPY --from=build /var/log/apache2     /var/log/apache2

EXPOSE 80
EXPOSE 443

ENTRYPOINT [ "/usr/sbin/apache2ctl", "-D", "FOREGROUND" ]
