FROM ubuntu:24.04
LABEL role=development

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
    cron \
    curl \
    git \
    iputils-ping \
    jq \
    jsonlint \
    openssh-client \
    patch \
    plocate \
    rsync \
    sudo \
    telnet \
    unzip \
    vim \
    wget \
    xz-utils \
    yamllint \
    zip

RUN DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
    clamav \
    mysql-client \
    nodejs \
    npm

RUN DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
    php8.3-cli \
    php8.3-apcu \
    php8.3-bcmath \
    php8.3-bz2 \
    php8.3-common \
    php8.3-curl \
    php8.3-gd \
    php8.3-gearman \
    php8.3-gmp \
    php8.3-igbinary \
    php8.3-imagick \
    php8.3-intl \
    php8.3-ldap \
    php8.3-mailparse \
    php8.3-maxminddb \
    php8.3-mbstring \
    php8.3-memcache \
    php8.3-memcached \
    php8.3-mongodb \
    php8.3-msgpack \
    php8.3-mysql \
    php8.3-oauth \
    php8.3-odbc \
    php8.3-opcache \
    php8.3-pcov \
    php8.3-ps \
    php8.3-pspell \
    php8.3-psr \
    php8.3-readline \
    php8.3-redis \
    php8.3-smbclient \
    php8.3-soap \
    php8.3-solr \
    php8.3-sqlite3 \
    php8.3-ssh2 \
    php8.3-stomp \
    php8.3-sybase \
    php8.3-tideways \
    php8.3-tidy \
    php8.3-uploadprogress \
    php8.3-uuid \
    php8.3-xdebug \
    php8.3-xml \
    php8.3-xmlrpc \
    php8.3-xsl \
    php8.3-yaml \
    php8.3-zip \
    php8.3-zmq

RUN DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
    composer

# Create the 'developer' user.
RUN adduser --shell /bin/bash developer
RUN usermod -aG www-data developer
RUN echo 'developer ALL=(ALL:ALL) NOPASSWD: ALL' | tee /etc/sudoers.d/developer

# Configure preferences.
COPY rootfs/home/developer/.vimrc /home/developer/.vimrc
COPY rootfs/etc/profile.d/* /etc/profile.d/
RUN cat /etc/profile.d/PS1.sh | tee -a /home/developer/.bashrc

USER developer
WORKDIR /home/developer

CMD [ "sleep", "infinity" ]
